sudo: false
cache: bundler
language: ruby

rvm:
  - 2.2.3
  - 2.2.0
  - 2.1.7
  - 2.1.0
  - 2.0.0-p647
  - 2.0.0
  - 1.9.3
  - ruby
  - ruby-head
  - jruby
  - jruby-19mode
  - jruby-head
  - rbx-2
  - rbx-head

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-head