site_name: RingCentral SDK for Ruby
site_url: https://github.com/grokify/ringcentral-sdk-ruby
repo_url: https://github.com/grokify/ringcentral-sdk-ruby.git
docs_dir: docs
theme: readthedocs
pages:
# Introduction:
- ['index.md', 'About', 'RingCentral SDK']
- ['quickstart.md', 'About', 'Quickstart']

## Authorization:
- ['usage/authorization/Authorization.md', 'Authorization', 'Authorization']

## Messaging:
- ['usage/messages/Call-Recordings.md', 'Messaging', 'Call Recordings']
- ['usage/messages/SMS-Messages.md', 'Messaging', 'SMS Messages']
- ['usage/messages/Fax-Messages.md', 'Messaging', 'Fax Messages']

## Voice:
- ['usage/voice/Click-To-Call.md', 'Voice', 'Click-To-Call']

## Notifications:
- ['usage/notifications/Subscriptions.md', 'Notifications', 'Subscriptions']